### ISSUE TITLE
torch version 1.5.0 giving: ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

### ISSUE THREAD

**Issue by amirzamli** [TideDancer/DTWNet#3]
Hi, thanks for providing the code for these models. I read the paper and I am impressed. 

I tried using this with my current project, however it is not supported by torch anymore as torch.utils.ffi is deprecated.
I know that is is much to ask for but is there any chance that this will be ported to the new cpp extensions? 

Thanks

**Comment by TideDancer** [comment]
Thank you for your interest. I notice that this was depreciated too. I will try to move it to the new cpp extension, but cannot guarantee to finish that in time. Sorry for the inconvenience.

**Comment by mohammadahmadi96** [comment]
Hello 
I've got this error to, then change it to torch.utils.cpp_extension but now I got this error when I try to run  python build_dp.py as instruction  : 

raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance

I've tried to use the old and different version of pytorch as I discovered after searching but it didnt solve. 

Would you please help me what should I do ?

Thanks a lot.
