### ISSUE TITLE
Some question about section 6.1

### ISSUE THREAD

**Issue by peter943** [TideDancer/DTWNet#4]
Hi,
I have learnt your paper these day, which is very enlightening to me. A synthetic dataset is generated in this Section. I found three similar train/test splits in the download file.  I am not quite sure which one corresponds. I try to reproduce the results in this Section, but  I do not know the appropriate parameters setting for the convolution network used in this Section. Could you please give me some help?

**Comment by TideDancer** [comment]
Hi, Thanks for your interest. To reproduce section 6.1, you can simply use synthetic_TRAIN and synthetic_TEST. The one ending with _squaretri is the same file, sorry for the confusion. The convolution net only has one convolution kernel. It also appends a 3-layer MLP. The details of params can be found in the configs/config_cnn.py file and the Model.py file (the CONV_MLP class).
