### ISSUE TITLE
 The cuda version 

### ISSUE THREAD

**Issue by peter943** [TideDancer/DTWNet#5]
Hi, 
  Thanks for your code. I have a question about the code. I ran your code according to the instructions. I found it to be running on a CPU rather than a GPU. I do not know if  that is normal? I tried to put the model on gpu by 'to(torch.device("cuda:1"))' . But I found the running time was longer than before. Maybe I did something wrong. Could you please help me to run the code on a GPU?  Thanks a lot.

**Comment by TideDancer** [comment]
Hi, the code is indeed running on CPU only. The implementation of CUDA code is not done yet. If simply put to cuda device, it will have no gains as the core part of backpropogation is only using CPU. Thanks.
